### ISSUE TITLE
Unable to trigger on iOS or Android

### ISSUE THREAD

**Issue by apokusin** [Nidilap/expo-alarm-module#2]
I'm unable to use the package in my managed workflow expo app.

# Steps to reproduce
1. install dependency
2. add permissions to app config
3. create new dev build (`expo run:android`)
4. add example code to app
5. press alarm button

# expected outcome
Alarm is triggered in 60 seconds

# outcome
App crashes

For what it's worth, the example apps also do not build or launch.

```
 ERROR  Your app just crashed. See the error below.
java.lang.RuntimeException: Unable to start service com.expoalarmmodule.AlarmService@ed7c5eb with Intent { cmp=co.domain.app/com.expoalarmmodule.AlarmService (has extras) }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c59933d 21371:co.domain.app/u0a190} targetSDK=34
  android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4839)
  android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
  android.os.Handler.dispatchMessage(Handler.java:106)
  android.os.Looper.loopOnce(Looper.java:205)
  android.os.Looper.loop(Looper.java:294)
  android.app.ActivityThread.main(ActivityThread.java:8177)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c59933d 21371:co.domain.app/u0a190} targetSDK=34
  android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
  android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
  android.os.Parcel.readParcelableInternal(Parcel.java:4870)
  android.os.Parcel.readParcelable(Parcel.java:4852)
  android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
  android.os.Parcel.createException(Parcel.java:3041)
  android.os.Parcel.readException(Parcel.java:3024)
  android.os.Parcel.readException(Parcel.java:2966)
  android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
  android.app.Service.startForeground(Service.java:775)
  com.expoalarmmodule.AlarmService.onStartCommand(AlarmService.java:41)
  android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
  android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
  android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
  android.os.Handler.dispatchMessage(Handler.java:106)
  android.os.Looper.loopOnce(Looper.java:205)
  android.os.Looper.loop(Looper.java:294)
  android.app.ActivityThread.main(ActivityThread.java:8177)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by apokusin** [comment]
It seems this requires bare workflow, but is it possible to add a config plugin to handle modifications to AndroidManifest?

**Comment by Nidilap** [comment]
Hello.
It is supposed to work with expo dev-client.
Can you give me the details of the expo version and node version you are running?

Are you using expo install to install the library?

**Comment by apokusin** [comment]
I am on expo 50 and node 20

I installed with npx expo install

**Comment by Nidilap** [comment]
I'll take a look at what is happening. Seems like it is not working with expo managed workflow, only with expo development build and expo bare workflow.

**Comment by apokusin** [comment]
Yeah I think there is a foreground service required on android (which notifee supports)

I'm not sure about iOS

**Comment by Nidilap** [comment]
Hello, I corrected the expo plugin, now it should be working in the new version 1.1.11.
Can you test to see if it is working for you?

**Comment by apokusin** [comment]
iOS Simulator:
- triggers notification once
- unable to trigger subsequently
- tried `removeAllAlarms` to clear out any stale info, no improvement

Android simulator:
- notification plays
- app crashes with the same log output as in the original issue description (No foreground service)

Building on my physical devices and will follow up with results

**Comment by apokusin** [comment]
Same issue with iOS physical device. It seems both platforms are able to trigger the first notification, but there's an issue with how it's handled. It might be related to the foreground service, as I know notifee requires some extra configuration in order to handle notification actions like "snooze".

**Comment by apokusin** [comment]
iOS:

I've played around with the code and built out a component from scratch rather than using the README example. it seems the firing of the alarm is working as expected. I misunderstood the example to be creating or updating a new alarm rather than referencing the previously created alarm.

**Comment by apokusin** [comment]
iOS: It also seems the minimum time period for scheduling alarms is 1 minute. So setting an alarm for 5:15:05 and 5:15:10 will only have one alarm trigger. I'm not sure if this is obvious so it might be worth mentioning in the docs.

**Comment by Nidilap** [comment]
Seems like an issue with 

> iOS Simulator:
> 
> * triggers notification once
> * unable to trigger subsequently
> * tried `removeAllAlarms` to clear out any stale info, no improvement
> 
> Android simulator:
> 
> * notification plays
> * app crashes with the same log output as in the original issue description (No foreground service)
> 
> Building on my physical devices and will follow up with results

In android, seems like an issue with android 14. I'll take a look to see how to correct this. In iOS, there are some limitations to what can be done with alarms (it is not really an alarm, but a notification), so I need to see if there's a way to correct it.

**Comment by Nidilap** [comment]
> iOS:
> 
> I've played around with the code and built out a component from scratch rather than using the README example. it seems the firing of the alarm is working as expected. I misunderstood the example to be creating or updating a new alarm rather than referencing the previously created alarm.

There is an example in the source folder that can be helpful with the usage of the alarm. The README.md does not have all functions.

**Comment by apokusin** [comment]
Thanks, I've been able to get the alarms to trigger more reliably on iOS. However, there are still issues with audio not playing and occassionally the app will crash if launched after a while of being in the background. 

iOS does have some oddities with regards to alarms and this flutter package seems to adjust for these gracefully. https://pub.dev/packages/alarm

Hope that's helpful!

**Comment by Nidilap** [comment]
Yeah that's helpful, thanks!
I'll try to take a look in the android problem this week, but the IOS will take some time to fix.

**Comment by Nidilap** [comment]
Hello.

Fixed the problem in android. It was some things that changed in Android 14.
Should be working now in version 1.1.13 of the library.

**Comment by apokusin** [comment]
Amazing, thank you. I've tested it on an Android emulator using Pixel 7 with APIs API 24-34. 

API 24, 25: Fails to set alarm with this error:
```
Could not invoke ExpoAlarmModule.set

null

Failed resolution of: Ljava/time/ZonedDateTime;

Didn't find class "java.time.ZonedDateTime" on path: DexPathList[zip fil "/data/app/app.apk"…
```

API 26, 27: Alarm triggers, notification triggers. Alarm notification sound is not the custom sound, seems like the built in alarm? Or the package doesn't use a bell.mp3 and Android always uses the built in sound. I mostly use iOS so I'm not sure. Either way it'd be nice if the sound was customizable. (expo-notification has a config plugin which could  be a good example)

API 28, 29, 30, 31, 33, 34: Alarm triggers, notification is shown.

Other issues:
- The app crashes when opened from the background. This might be an issue with Notifee which is used in the app as well, currently investigating.
- Alarm notification doesn't have a "snooze" action.
- If the app is open, a toast notification is shown with the text "received alarm <id>". It would be nice if this text was customizable or at least set to a more user-friendly message.

**Comment by Nidilap** [comment]
> Amazing, thank you. I've tested it on an Android emulator using Pixel 7 with APIs API 24-34.
> 
> API 24, 25: Fails to set alarm with this error:
> 
> ```
> Could not invoke ExpoAlarmModule.set
> 
> null
> 
> Failed resolution of: Ljava/time/ZonedDateTime;
> 
> Didn't find class "java.time.ZonedDateTime" on path: DexPathList[zip fil "/data/app/app.apk"…
> ```
> 
> API 26, 27: Alarm triggers, notification triggers. Alarm notification sound is not the custom sound, seems like the built in alarm? Or the package doesn't use a bell.mp3 and Android always uses the built in sound. I mostly use iOS so I'm not sure. Either way it'd be nice if the sound was customizable. (expo-notification has a config plugin which could be a good example)
> 
> API 28, 29, 30, 31, 33, 34: Alarm triggers, notification is shown.
> 
> Other issues:
> 
> * The app crashes when opened from the background. This might be an issue with Notifee which is used in the app as well, currently investigating.
> * Alarm notification doesn't have a "snooze" action.
> * If the app is open, a toast notification is shown with the text "received alarm ". It would be nice if this text was customizable or at least set to a more user-friendly message.

Hello, I have been quite busy the last few days, sorry for not answering before.

The alarm just works from API 26 onwards (Android 8+). I will put this in the documentation. I didn't implement Android 7 support because I use ZonedDateTime in the library, that is not available before API 26.

I intend to implement snooze action and custom sound.
The sound for now is the default sound of the cellphone.

I removed the "received alarm" text that is shown in the new version "1.1.14". The idea is to control how the alarm is received in the react native part. This was just a remnant of development.

**Comment by apokusin** [comment]
Great, I plan to use this as the defacto alarm module in my RN+Expo app so let me know if you'd like collaboration on any of these issues.

**Comment by apokusin** [comment]
Seems like the core of this issue is solved so I'll close this one out and make new issues for the remaining requests.

**Comment by Nidilap** [comment]
> Seems like the core of this issue is solved so I'll close this one out and make new issues for the remaining requests.

Ok great!
